title: Franz Geffke
description:
baseurl: ""
url: "https://f-a.nz"
bitcoin: 1MfbsSexrSb74ZDQPqMrKGzZhRubHZBkCB

# Build settings
markdown: kramdown
theme: minima

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'

gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate-v2

exclude:
  - Gemfile
  - Gemfile.lock

collections:
- gist
- dev
- projects
- clients
- testimonials

collections:
  gist:
    output: true
    permalink: /gist/:title/
  dev:
    output: true
    permalink: /dev/:title/
  work:
    output: true
    permalink: /work/:title/
  clients:
    output: true
    permalink: /client/:title/
  testimonials:
    output: false

assets:
  sources:
    - /assets/css
    - /assets/js
    - /assets/swipebox/css
    - /assets/swipebox/js
