title: Franz Geffke
description:
baseurl: ""
url: "https://f-a.nz"
bitcoin: 1MfbsSexrSb74ZDQPqMrKGzZhRubHZBkCB

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'

gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate-v2

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - .gitignore
  - node_modules
  - vendor
  - s3_website.yml
  - .gitlab-ci.yml
  - gulpfile.js
  - src
  - README.md

collections:
- gist
- dev
- projects
- clients
- testimonials

collections:
  gist:
    output: true
    permalink: /gist/:title/
  dev:
    output: true
    permalink: /dev/:title/
  work:
    output: true
    permalink: /work/:title/
  clients:
    output: true
    permalink: /client/:title/
  testimonials:
    output: false
